#! /usr/bin/env python2

# Developed by Olivia Lucca Fraser
# for Tenable Network Security

from sys import argv
import argparse

def step(row):
    call_or_ret=row.split(" ")[0]
    if (call_or_ret == "call"):
        return 1
    elif (call_or_ret == "ret"):
        return -1
    else:
        return 0

def frame(row):
    fr = row.split(" ")[1].split("(")[0]
    if (fr == ""):
        fr = "INTERNAL"
    return fr

def prettify_trace (filename, depth, focus, show_origins):
    tracerows=[r.split("(TRACE) ")[1] for r in open(filename).readlines()]
    indent=0
    r="MAIN"
    frame_stack=[r]
    for row in tracerows:
        s = step(row)
        if (s == 1):
            frame_stack.append(frame(row))
        elif (s == -1):
            try:
                r = frame_stack.pop()
            except:
                print "<< call stack anomaly >>"
        if ((depth == 0 or depth > indent) and
            (focus == "" or (focus in [r]+frame_stack))):
            print ("  "*max(0,indent))+row[:-1],
            if (s == -1):
                print "[from "+r+"]"
                r=""
            elif (show_origins and len(frame_stack) > 1):
                print "[from "+frame_stack[-2]+"]"
            else:
                print
        indent += s

def main ():
    parser = argparse.ArgumentParser(description =
                                     "Reconstruct call stack from nasl -T"+
                                     " trace, and structure trace output "+
                                     " accordingly.")
    parser.add_argument("tracefile", 
                        help="the output file generated by nasl -T")
    parser.add_argument("--depth", "-d", metavar="<calls deep>", type=int,
                        default=0,
                        help="how deep to peer into the call"+
                        " stack, in absolute terms")
    parser.add_argument("--function", "-f", metavar="<function name>",
                        type=str,
                        default="",
                        help="if you would like to restrict the"+
                        " view to just one function, name it")
    parser.add_argument("--sources", "-s", type=bool, default=False,
                        metavar="<True|False>",
                        help="display the name of the function from which each function is called")
    args = parser.parse_args()
    prettify_trace(args.tracefile, args.depth, args.function, args.sources)

if __name__ == "__main__":
    main()
